@startuml
(注文作成中)-->(注文確認まち):ユーザーが商品をカートに追加する
(注文確定)-->(支払いまち):ユーザーが注文を確定
(支払い完了)-->(配送準備中):支払いが完了
(配送完了)-->(配送済み):配送が完了
(配送済み)-->(キャンセル済み):ユーザーが注文をキャンセル
(支払いまち)-->(支払い失敗):支払い失敗
(支払い失敗)-->(支払いまち)
@enduml